const basicConfigParam =  {     // 新建URL列表，新接口可以随时补充
    'getUserList':{
        name:'用户列表',
        value:'/api/v1/user/queryUserListPage',
        type:"post"
    },
    'userAdd':{
        name:'添加用户',
        value:'/api/v1/user/saveUser',
        type:"post",
    },
    'userEdit':{
        name:'编辑用户',
        value:'/api/v1/user/editUser',
        type:"post",
    },
    'userDel':{
        name:'删除用户',
        value:'/api/v1/user/deleteUser',
        type:"get"
    },
    'getUserRoleSetList':{
        name:'角色设置列表',
        value:'/api/v1/userRole/users/userRoleList',
        type:"get"
    },
    'setUserSelectRole':{
        name:'设置用户角色',
        value:'/api/v1/userRole/users/userRoleManage',
        type:"post",
    },
    'getUserModuleList':{
        name:'获取角色模块列表',
        value:'/api/v1/userModule/module/userModuleList',
        type:"get"
    },
    'setUserModule':{
        name:'设置用户模块',
        value:'/api/v1/userModule/module/userModuleManage',
        type:"post",
    },
    'getUserProjectList':{
        name:'获取用户项目列表',
        value:'/api/v1/project-manager/queryAllList',
        type: "get",
    },
    'getUserProjectId':{
        name:'获取用户拥有模块的项目编码列表',
        value:'/api/v1/moduleProject/getProjectIdByUserAndModule',
        type: "get",
    },
    'setUserProjectRights': {
        name:'设置用户的项目管理权限',
        value:'/api/v1/moduleProject/moduleProjectManage',
        type: "post",
    },

    // 'resetPwd':{
    //     name:'重置用户密码',
    //     value:'/api/v1/users/resetPwd',
    //     type:"post"
    // },
    //
    'modulesList':{
        name:'模块列表',
        value:'/api/v1/module/queryModuleListPage',
        type:"post"
    },
    'getmodulesAllList':{
        name:'模块列表',
        value:'/api/v1/module/queryModuleList',
        type:"get"
    },
    'moduleAdd':{
        name:'添加模块',
        value:'/api/v1/module/saveModule',
        type:"post",
        ContentType:'post'
    },
    'moduleEdit':{
        name:'编辑模块',
        value:'/api/v1/module/editModule',
        type:"post",
        ContentType:'post'
    },
    'modulesDel':{
        name:'删除模块',
        value:'/api/v1/module/deleteModule',
        type:"get"
    },
//
    'userTypeList':{
        name:'用户类型列表',
        value:'/api/v1/user/queryUserListPage',
        type:"get"
    },
    'userTypeModuleSet':{
        name:'用户类型设置',
        value:'/api/v1/userTypeSquareds/userTypeSquaredSet',
        type:"post"
    },
    'organizationList':{
        name:'组织机构列表',
        value:'/api/v1/Org/queryOrgList',
        type:"post"
    },
    'organizationPageList':{
        name:'组织机构列表',
        value:'/api/v1/Org/queryOrgListPage',
        type:"post"
    },
    'organizationTreeList':{
        name:'组织机构列表树',
        value:'/api/v1/Org/queryAllOrgTree',
        type:"post"
    },
    'organizationAdd':{
        name:'添加组织机构',
        value:'/api/v1/Org/saveOrg',
        type:"post"
    },
    'organizationEdit':{
        name:'编辑组织机构',
        value:'/api/v1/Org/updateOrg',
        type:"post"
    },
    'delorganization':{
        name:'删除组织机构',
        value:'/api/v1/Org/deleteOrg',
        type:"get"
    },
    'projectManagementList': {
        name:'项目管理列表',
        value:'/api/v1/project-manager/queryListPage',
        type:'post'
    },
    'projectManagementAdd':{
        name:'项目新增',
        value:'/api/v1/project-manager/add',
        type:'post'
    },
    'getCityList':{
        name:'城市列表',
        value:'/api/v1/city/queryList',
        type:'post'
    },
    'dictionaryTypeList':{
        name:'数据字典类型列表',
        value:'/api/v1/dictType/findAll',
        type:'post'
    },
    'delDictionaryType':{
        name:'删除数据字典类型',
        value:'/api/v1/dictType/delete',
        type:'get'
    },
    'dictionaryTypeAdd':{
        name:'添加数据字典类型',
        value:'/api/v1/dictType/add',
        type:'post'
    },
    'dictionaryTypeEdit':{
        name:'编辑数据字典类型',
        value:'/api/v1/dictType/edit',
        type:'post',
    },
    'dictionaryDetailList':{
        name:'数据字典明细列表',
        value:'/api/v1/dictEntry/findDictDetails',
        type:'post'
    },
    'dictionaryDetailAdd':{
        name:'添加数据字典明细',
        value:'/api/v1/dictEntry/add',
        type:'post'
    },
    'dictionaryDetailEdit':{
        name:'编辑数据字典明细',
        value:'/api/v1/dictEntry/edit',
        type:'post'
    },
    'getDictTypeData':{
        name:'数据字典类型',
        value:'/api/v1/dictType/DictTypeList',
        type:'post'
    },
    'delDictionaryDetail':{
        name:'删除数据字典明细',
        value:'/api/v1/dictEntry/delete',
        type:'get'
    },

    'getRoleManageList':{
        name:'角色管理列表',
        value:'/api/v1/role/queryPage',
        type:'post'
    },
    'roleAdd':{
        name:'添加角色',
        value:'/api/v1/role/add',
        type:'post'
    },
    'delRole':{
        name:'删除角色',
        value:'/api/v1/role/delete',
        type:'post'
    },
    'editRole':{
        name:'编辑角色',
        value:'/api/v1/role/edit',
        type:'post'
    },
    'getRoleMenuCheckedList':{
        name:'获取角色菜单选中项',
        value:'/api/v1/roleMenu/getRoleMenuRelactionByUserCode',
        type:'get'
    },
    'setRoleMenus':{
        name:'设置角色菜单',
        value:'/api/v1/roleMenu/roleMenuManage',
        type:'post'
    },
    //
    'getAllmenuManageList':{
        name:'菜单管理列表',
        value:'/api/v1/menu/getAllMouduleMenuTrees',
        type:'get'
    },
    'getMenuManageList':{
        name:'菜单管理列表获取单个',
        value:'/api/v1/menu/getAllMenuTreesByModule',
        type:'get'
    },
    'getMenuManageListByUser':{
        name:'根据用户获取菜单',
        value:'/api/v1/menu/getUserLeftMenuTrees',
        type:'get'
    },
    'menuAdd':{
        name:'添加菜单',
        value:'/api/v1/menu/add',
        type:'post'
    },
    'delMenu':{
        name:'删除菜单',
        value:'/api/v1/menu/del',
        type:'post'
    },
    'editMenu':{
        name:'编辑菜单',
        value:'/api/v1/menu/edit',
        type:'post'
    },
}
export {basicConfigParam}
